# Generated by Django 4.2.3 on 2023-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.SmallIntegerField(verbose_name='Категория')),
                ('author', models.CharField(max_length=20, verbose_name='Автор')),
                ('location', models.CharField(max_length=255, verbose_name='Локация товара')),
                ('auction', models.BooleanField(verbose_name='Торг')),
            ],
        ),
    ]
