# Generated by Django 4.2.3 on 2023-08-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_adverts', '0003_advertisement_user_alter_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
    ]
