# Generated by Django 4.2.3 on 2023-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_adverts', '0007_alter_advertisement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='my_adverts', verbose_name='Фото'),
        ),
    ]
